import { Stock } from '../types/stock';

const logo = (ticker: string) =>
  `https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/${ticker}.png`;

export const DJIA_STOCKS: Stock[] = [
  { id: 'AAPL', ticker: 'AAPL', company_name: 'Apple Inc.', sector: 'Technology', description: 'Designs and sells consumer electronics, software, and services including iPhone, Mac, and the App Store.', logo_url: logo('AAPL') },
  { id: 'AMGN', ticker: 'AMGN', company_name: 'Amgen Inc.', sector: 'Healthcare', description: 'Biotechnology company that discovers, develops, and delivers innovative human therapeutics for serious illnesses.', logo_url: logo('AMGN') },
  { id: 'AMZN', ticker: 'AMZN', company_name: 'Amazon.com Inc.', sector: 'Consumer Discretionary', description: 'Global leader in e-commerce, cloud computing via AWS, digital streaming, and artificial intelligence.', logo_url: logo('AMZN') },
  { id: 'AXP',  ticker: 'AXP',  company_name: 'American Express Co.', sector: 'Financials', description: 'Global financial services company offering credit cards, charge cards, and travel-related services worldwide.', logo_url: logo('AXP') },
  { id: 'BA',   ticker: 'BA',   company_name: 'Boeing Co.', sector: 'Industrials', description: 'Designs and manufactures commercial jetliners, military aircraft, satellites, and defense systems.', logo_url: logo('BA') },
  { id: 'CAT',  ticker: 'CAT',  company_name: 'Caterpillar Inc.', sector: 'Industrials', description: "World's leading manufacturer of construction and mining equipment, diesel engines, and industrial gas turbines.", logo_url: logo('CAT') },
  { id: 'CRM',  ticker: 'CRM',  company_name: 'Salesforce Inc.', sector: 'Technology', description: 'Cloud-based software company specializing in customer relationship management, analytics, and enterprise applications.', logo_url: logo('CRM') },
  { id: 'CSCO', ticker: 'CSCO', company_name: 'Cisco Systems Inc.', sector: 'Technology', description: 'Designs and sells networking hardware, software, telecommunications equipment, and cybersecurity solutions.', logo_url: logo('CSCO') },
  { id: 'CVX',  ticker: 'CVX',  company_name: 'Chevron Corp.', sector: 'Energy', description: "One of the world's leading integrated energy companies, engaged in oil and gas exploration, production, and refining.", logo_url: logo('CVX') },
  { id: 'DIS',  ticker: 'DIS',  company_name: 'The Walt Disney Co.', sector: 'Communication Services', description: 'Global entertainment and media company operating theme parks, film studios, streaming services, and broadcast networks.', logo_url: logo('DIS') },
  { id: 'DOW',  ticker: 'DOW',  company_name: 'Dow Inc.', sector: 'Materials', description: 'Leading materials science company delivering performance materials, industrial intermediates, and plastics.', logo_url: logo('DOW') },
  { id: 'GS',   ticker: 'GS',   company_name: 'Goldman Sachs Group Inc.', sector: 'Financials', description: 'Global investment banking, securities, asset management, and consumer banking firm.', logo_url: logo('GS') },
  { id: 'HD',   ticker: 'HD',   company_name: 'Home Depot Inc.', sector: 'Consumer Discretionary', description: "World's largest home improvement retailer, selling building materials, appliances, and garden products.", logo_url: logo('HD') },
  { id: 'HON',  ticker: 'HON',  company_name: 'Honeywell International Inc.', sector: 'Industrials', description: 'Diversified technology and manufacturing company serving aerospace, building technologies, and performance materials.', logo_url: logo('HON') },
  { id: 'IBM',  ticker: 'IBM',  company_name: 'IBM Corp.', sector: 'Technology', description: 'Multinational technology corporation offering cloud computing, AI via Watson, consulting, and enterprise software.', logo_url: logo('IBM') },
  { id: 'JNJ',  ticker: 'JNJ',  company_name: 'Johnson & Johnson', sector: 'Healthcare', description: 'Global healthcare company operating across pharmaceuticals, medical devices, and consumer health products.', logo_url: logo('JNJ') },
  { id: 'JPM',  ticker: 'JPM',  company_name: 'JPMorgan Chase & Co.', sector: 'Financials', description: 'Leading global financial services firm offering investment banking, commercial banking, and asset management.', logo_url: logo('JPM') },
  { id: 'KO',   ticker: 'KO',   company_name: 'Coca-Cola Co.', sector: 'Consumer Staples', description: "World's largest beverage company, offering more than 500 brands of sparkling and still beverages in over 200 countries.", logo_url: logo('KO') },
  { id: 'MCD',  ticker: 'MCD',  company_name: "McDonald's Corp.", sector: 'Consumer Discretionary', description: "World's largest fast-food restaurant chain, operating and franchising over 40,000 locations globally.", logo_url: logo('MCD') },
  { id: 'MMM',  ticker: 'MMM',  company_name: '3M Co.', sector: 'Industrials', description: 'Innovation company applying science to improve lives daily across safety, industrial, transportation, and healthcare markets.', logo_url: logo('MMM') },
  { id: 'MRK',  ticker: 'MRK',  company_name: 'Merck & Co. Inc.', sector: 'Healthcare', description: 'Global pharmaceutical company discovering and developing medicines, vaccines, biologic therapies, and animal health products.', logo_url: logo('MRK') },
  { id: 'MSFT', ticker: 'MSFT', company_name: 'Microsoft Corp.', sector: 'Technology', description: 'Global technology company offering cloud services via Azure, productivity software, gaming, and enterprise solutions.', logo_url: logo('MSFT') },
  { id: 'NKE',  ticker: 'NKE',  company_name: 'Nike Inc.', sector: 'Consumer Discretionary', description: "World's largest designer, marketer, and distributor of athletic footwear, apparel, equipment, and accessories.", logo_url: logo('NKE') },
  { id: 'NVDA', ticker: 'NVDA', company_name: 'NVIDIA Corp.', sector: 'Technology', description: 'Designs GPUs for gaming, professional visualization, data centers, and AI, and produces system-on-chip units.', logo_url: logo('NVDA') },
  { id: 'PG',   ticker: 'PG',   company_name: 'Procter & Gamble Co.', sector: 'Consumer Staples', description: 'Global consumer goods company offering branded products across beauty, grooming, health care, fabric, and home care.', logo_url: logo('PG') },
  { id: 'SHW',  ticker: 'SHW',  company_name: 'Sherwin-Williams Co.', sector: 'Materials', description: 'Leading manufacturer, distributor, and retailer of paints, coatings, and related products worldwide.', logo_url: logo('SHW') },
  { id: 'TRV',  ticker: 'TRV',  company_name: 'Travelers Companies Inc.', sector: 'Financials', description: 'Leading provider of commercial and personal property and casualty insurance products and services.', logo_url: logo('TRV') },
  { id: 'UNH',  ticker: 'UNH',  company_name: 'UnitedHealth Group Inc.', sector: 'Healthcare', description: 'Diversified health care company offering health benefits and services through UnitedHealthcare and Optum.', logo_url: logo('UNH') },
  { id: 'V',    ticker: 'V',    company_name: 'Visa Inc.', sector: 'Financials', description: "World's leader in digital payments, facilitating transactions between consumers, merchants, financial institutions, and governments.", logo_url: logo('V') },
  { id: 'WMT',  ticker: 'WMT',  company_name: 'Walmart Inc.', sector: 'Consumer Staples', description: "World's largest retailer operating hypermarkets, discount department stores, and grocery stores globally.", logo_url: logo('WMT') },

  // ─── Cryptocurrencies ──────────────────────────────────────────────────────
  // finnhub_symbol: Binance pair for Finnhub REST quote + WebSocket
  // yahoo_symbol:   Yahoo Finance ticker for candle data

  { id: 'BTC',   ticker: 'BTC',   company_name: 'Bitcoin',    sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:BTCUSDT',   yahoo_symbol: 'BTC-USD',   description: 'The original cryptocurrency and largest by market cap. A decentralized digital currency secured by proof-of-work, designed as a peer-to-peer store of value and medium of exchange.',                                                                              logo_url: 'https://assets.coingecko.com/coins/images/1/large/bitcoin.png' },
  { id: 'ETH',   ticker: 'ETH',   company_name: 'Ethereum',   sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:ETHUSDT',   yahoo_symbol: 'ETH-USD',   description: 'The leading programmable blockchain platform. Ethereum hosts the majority of decentralized finance (DeFi), NFTs, and smart contracts running on its proof-of-stake network.',                                                                                                       logo_url: 'https://assets.coingecko.com/coins/images/279/large/ethereum.png' },
  { id: 'BNB',   ticker: 'BNB',   company_name: 'BNB',        sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:BNBUSDT',   yahoo_symbol: 'BNB-USD',   description: 'Native token of the BNB Chain ecosystem, used to pay fees on Binance Exchange and BNB Smart Chain. Powers one of the most active blockchain networks for DeFi applications.',                                                                                                       logo_url: 'https://assets.coingecko.com/coins/images/825/large/bnb-icon2_2x.png' },
  { id: 'SOL',   ticker: 'SOL',   company_name: 'Solana',     sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:SOLUSDT',   yahoo_symbol: 'SOL-USD',   description: 'A high-performance Layer 1 blockchain known for sub-second finality and low transaction fees. Solana supports a wide ecosystem of DeFi protocols, NFT marketplaces, and consumer apps.',                                                                                                 logo_url: 'https://assets.coingecko.com/coins/images/4128/large/solana.png' },
  { id: 'XRP',   ticker: 'XRP',   company_name: 'XRP',        sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:XRPUSDT',   yahoo_symbol: 'XRP-USD',   description: "Ripple's digital asset designed for fast, low-cost international money transfers. XRP serves as a bridge currency in RippleNet, enabling real-time gross settlement between financial institutions.",                                                                                       logo_url: 'https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png' },
  { id: 'ADA',   ticker: 'ADA',   company_name: 'Cardano',    sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:ADAUSDT',   yahoo_symbol: 'ADA-USD',   description: 'A proof-of-stake blockchain platform built on peer-reviewed academic research. Cardano aims to provide a secure and scalable infrastructure for decentralized applications and digital identity.',                                                                                         logo_url: 'https://assets.coingecko.com/coins/images/975/large/cardano.png' },
  { id: 'AVAX',  ticker: 'AVAX',  company_name: 'Avalanche',  sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:AVAXUSDT',  yahoo_symbol: 'AVAX-USD',  description: 'A fast, low-cost smart contract platform with sub-second transaction finality. Avalanche uses a novel three-chain architecture and supports custom subnets, making it a top choice for institutional DeFi.',                                                                                logo_url: 'https://assets.coingecko.com/coins/images/12559/large/Avalanche_Circle_RedWhite_Trans.png' },
  { id: 'DOT',   ticker: 'DOT',   company_name: 'Polkadot',   sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:DOTUSDT',   yahoo_symbol: 'DOT-USD',   description: 'A multi-chain network that enables different blockchains to transfer messages and value in a trust-free fashion. Polkadot connects specialized blockchains called parachains into a unified network.',                                                                                      logo_url: 'https://assets.coingecko.com/coins/images/12171/large/polkadot.png' },
  { id: 'LINK',  ticker: 'LINK',  company_name: 'Chainlink',  sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:LINKUSDT',  yahoo_symbol: 'LINK-USD',  description: 'The leading decentralized oracle network that connects smart contracts with real-world data, APIs, and payment systems. LINK token is used to pay node operators for delivering off-chain data.',                                                                                           logo_url: 'https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png' },
  { id: 'MATIC', ticker: 'MATIC', company_name: 'Polygon',    sector: 'Cryptocurrency', finnhub_symbol: 'BINANCE:MATICUSDT', yahoo_symbol: 'MATIC-USD', description: "Ethereum's leading Layer 2 scaling solution offering fast, cheap transactions while inheriting Ethereum's security. Polygon's PoS chain supports a vast ecosystem of games, DeFi, and NFT applications.",                                                                                 logo_url: 'https://assets.coingecko.com/coins/images/3890/large/polygon.png' },

  // ─── ETFs ──────────────────────────────────────────────────────────────────

  { id: 'SPY',  ticker: 'SPY',  company_name: 'SPDR S&P 500 ETF Trust',              sector: 'ETF', description: "The most-traded ETF in the world, tracking the S&P 500 index of large-cap U.S. stocks. Provides instant diversification across 500 of America's biggest companies in a single trade.",                                 logo_url: logo('SPY') },
  { id: 'QQQ',  ticker: 'QQQ',  company_name: 'Invesco QQQ Trust',                   sector: 'ETF', description: 'Tracks the Nasdaq-100, the 100 largest non-financial companies on the Nasdaq. Heavily weighted toward mega-cap technology, making it a benchmark for tech-sector growth.',                                              logo_url: 'https://logo.clearbit.com/invesco.com' },
  { id: 'IWM',  ticker: 'IWM',  company_name: 'iShares Russell 2000 ETF',            sector: 'ETF', description: 'Tracks the Russell 2000 index of U.S. small-cap stocks. Exposure to roughly 2,000 smaller companies, offering diversified access to domestically-focused businesses and higher-growth potential.',                          logo_url: 'https://logo.clearbit.com/ishares.com' },
  { id: 'DIA',  ticker: 'DIA',  company_name: 'SPDR Dow Jones Industrial Avg ETF',   sector: 'ETF', description: "Tracks the 30-stock Dow Jones Industrial Average, the oldest and most-cited U.S. equity benchmark. Holds the same blue-chip companies featured in Stockr's core swipe deck.",                                            logo_url: logo('DIA') },
  { id: 'VTI',  ticker: 'VTI',  company_name: 'Vanguard Total Stock Market ETF',     sector: 'ETF', description: 'Broad exposure to the entire U.S. equity market — large, mid, small, and micro-cap — in one fund. One of the most widely held ETFs by long-term, buy-and-hold investors.',                                             logo_url: 'https://logo.clearbit.com/vanguard.com' },
  { id: 'VOO',  ticker: 'VOO',  company_name: 'Vanguard S&P 500 ETF',                sector: 'ETF', description: "Vanguard's low-cost version of the S&P 500 index fund. Favored by passive investors for its rock-bottom expense ratio and reliable tracking of America's 500 largest companies.",                                        logo_url: 'https://logo.clearbit.com/vanguard.com' },
  { id: 'GLD',  ticker: 'GLD',  company_name: 'SPDR Gold Shares',                    sector: 'ETF', description: 'The largest gold-backed ETF, giving investors direct exposure to the price of gold bullion without physically storing it. Often used as a hedge against inflation and market downturns.',                                logo_url: logo('GLD') },
  { id: 'TLT',  ticker: 'TLT',  company_name: 'iShares 20+ Year Treasury Bond ETF', sector: 'ETF', description: 'Tracks long-duration U.S. Treasury bonds with maturities of 20 years or more. Highly sensitive to interest rate changes and widely used as a safe-haven asset and rate-direction trade.',                               logo_url: 'https://logo.clearbit.com/ishares.com' },
  { id: 'XLK',  ticker: 'XLK',  company_name: 'Technology Select Sector SPDR Fund', sector: 'ETF', description: 'Concentrated exposure to U.S. technology companies within the S&P 500, including software, hardware, semiconductors, and IT services. One of the top-performing sector ETFs of the past decade.',                       logo_url: logo('XLK') },
  { id: 'VNQ',  ticker: 'VNQ',  company_name: 'Vanguard Real Estate ETF',            sector: 'ETF', description: 'Tracks U.S. real estate investment trusts (REITs), offering exposure to commercial property, residential, industrial, and healthcare real estate. Provides income through REIT dividend distributions.',                  logo_url: 'https://logo.clearbit.com/vanguard.com' },
  { id: 'EEM',  ticker: 'EEM',  company_name: 'iShares MSCI Emerging Markets ETF',   sector: 'ETF', description: 'Tracks the MSCI Emerging Markets index, covering large and mid-cap equities across 24 developing economies including China, India, Brazil, and Taiwan. High growth potential with elevated geopolitical risk.',            logo_url: 'https://logo.clearbit.com/ishares.com' },
  { id: 'EFA',  ticker: 'EFA',  company_name: 'iShares MSCI EAFE ETF',               sector: 'ETF', description: 'Tracks the MSCI EAFE index of large and mid-cap developed-market stocks across Europe, Australasia, and the Far East. A core international diversifier for U.S.-based investors.',                                       logo_url: 'https://logo.clearbit.com/ishares.com' },
  { id: 'ARKK', ticker: 'ARKK', company_name: 'ARK Innovation ETF',                  sector: 'ETF', description: 'An actively managed ETF run by ARK Invest targeting disruptive innovation across genomics, AI, robotics, fintech, and space exploration. Known for high conviction, high volatility, high-growth bets.',                 logo_url: 'https://logo.clearbit.com/ark-funds.com' },
  { id: 'BND',  ticker: 'BND',  company_name: 'Vanguard Total Bond Market ETF',      sector: 'ETF', description: 'Broad exposure to the entire U.S. investment-grade bond market — government, corporate, and mortgage-backed securities. The benchmark choice for fixed-income allocation in a diversified portfolio.',                   logo_url: 'https://logo.clearbit.com/vanguard.com' },
  { id: 'VYM',  ticker: 'VYM',  company_name: 'Vanguard High Dividend Yield ETF',    sector: 'ETF', description: 'Tracks high dividend-yielding U.S. stocks, weighted toward value-oriented sectors like financials, healthcare, and consumer staples. Favored by income investors seeking reliable quarterly distributions.',              logo_url: 'https://logo.clearbit.com/vanguard.com' },
];
